-- Base
Contenedores = DISTINCTCOUNT(FactPlanActual[contenedor_id])

Contenedores En Puerto =
CALCULATE(
    [Contenedores],
    DimStatus[status_stage] = "PUERTO"
)

Contenedores En Patio =
CALCULATE(
    [Contenedores],
    DimStatus[status_stage] = "PATIO"
)

Contenedores En Bodega =
CALCULATE(
    [Contenedores],
    DimStatus[status_stage] = "BODEGA"
)

Alertas CAS =
CALCULATE(
    [Contenedores],
    FactPlanActual[alerta_cas] = TRUE()
)

CAS Vencidos =
CALCULATE(
    [Contenedores],
    FactPlanActual[cas_vencido] = TRUE()
)

Incidencias =
CALCULATE(
    [Contenedores],
    NOT ISBLANK(FactStatusDiario[tipo_incidencia]),
    FactStatusDiario[tipo_incidencia] <> "",
    FactStatusDiario[es_ultimo_status] = TRUE()
)

Pct Cumplimiento Grupasa =
DIVIDE(
    CALCULATE(
        [Contenedores],
        FactPlanActual[cumplimiento_grupasa] = "CUMPLE"
    ),
    CALCULATE(
        [Contenedores],
        FactPlanActual[cumplimiento_grupasa] IN {"CUMPLE", "INCUMPLE"}
    )
)

Pct Cumplimiento Galagans =
DIVIDE(
    CALCULATE(
        [Contenedores],
        FactPlanActual[cumplimiento_galagans] = "CUMPLE"
    ),
    CALCULATE(
        [Contenedores],
        FactPlanActual[cumplimiento_galagans] IN {"CUMPLE", "INCUMPLE"}
    )
)

Dias Prom Puerto a Patio = AVERAGE(FactPlanActual[dias_puerto_a_patio])

Dias Prom Patio a Bodega = AVERAGE(FactPlanActual[dias_patio_a_bodega])

Dias Prom Bodega a Deposito = AVERAGE(FactPlanActual[dias_bodega_a_deposito])

Errores Validacion = COUNTROWS(FactErroresValidacion)

Snapshots Status = COUNTROWS(FactStatusDiario)

Contenedores Unicos Historico = DISTINCTCOUNT(FactStatusDiario[contenedor_id])

Contenedores con Incidencia =
CALCULATE(
    DISTINCTCOUNT(FactStatusDiario[contenedor_id]),
    NOT ISBLANK(FactStatusDiario[tipo_incidencia]),
    FactStatusDiario[tipo_incidencia] <> "",
    FactStatusDiario[es_ultimo_status] = TRUE()
)

Semaforo CAS =
SWITCH(
    TRUE(),
    [CAS Vencidos] > 0, "Rojo",
    [Alertas CAS] > 0, "Amarillo",
    "Verde"
)

Ultima Fecha Snapshot = MAX(FactPlanActual[fecha_snapshot])
